ALTER TABLE DIAS ALTER COLUMN FECHAASOCIADA DATE;

ALTER TABLE MOVIMIENTOS ALTER COLUMN FECHAALTA DATE;
ALTER TABLE MOVIMIENTOS ALTER COLUMN FECHACONCRECION DATE;
ALTER TABLE OPERACIONES ALTER COLUMN FECHAALTA DATE;
ALTER TABLE OPERACIONES ALTER COLUMN FECHALIQUIDACION DATE;
